# SQLite database configuration
datasources.default.db-type=sqlite
datasources.default.driver-class-name=org.sqlite.JDBC
datasources.default.dialect=H2
datasources.default.url=jdbc:sqlite:${NETCENTRAL_SERVER_SQLITE_FILE:D:/ham/netcentral.db}?busy_timeout=10000&date_class=integer 
datasources.default.username=${NETCENTRAL_SERVER_SQLITE_USERNAME:netcentral}
datasources.default.password=${NETCENTRAL_SERVER_SQLITE_PASSWORD:netcentral}
datasources.default.hikari.maximum-pool-size=1
datasources.default.hikari.minimum-idle=0
liquibase.datasources.default.change-log=classpath\:db/liquibase-changelog-h2.xml

