FROM eclipse-temurin:21-jdk-alpine
RUN ["apk", "update"]
RUN ["apk", "add", "bash"]
RUN ["apk", "add", "sudo"]
RUN ["apk", "add", "openrc"]

RUN mkdir -p /run/openrc
RUN touch /run/openrc/softlevel

RUN ["apk", "add", "npm"]
RUN ["apk", "add", "libcap"]

ARG USER_UID=1000
ARG GROUP_GID=1000
ARG UNAME=netcentral
ARG GNAME=netcentralgroup
RUN addgroup -S -g ${GROUP_GID} ${GNAME} && \
    adduser -S -D -H -u ${USER_UID} -G ${GNAME} ${UNAME}

WORKDIR /netcentral
RUN mkdir -p /netcentral/tmp
RUN mkdir -p /netcentral/tmp/logs
RUN mkdir -p /netcentral/tmp/reports
RUN mkdir -p /netcentral/bin
RUN mkdir -p /netcentral/bin/ui

ADD installers/docker/split/image_files/ui_processes.sh /netcentral/bin/ui_processes.sh
RUN ["dos2unix", "/netcentral/bin/ui_processes.sh"]

ADD installers/docker/split/image_files/nc_setcap.sh /netcentral/bin/nc_setcap.sh
RUN ["dos2unix", "/netcentral/bin/nc_setcap.sh"]
RUN ["/netcentral/bin/nc_setcap.sh"]

ADD ui/net-central-ui/target/netcentral-ui-1.0.12.zip /netcentral/bin/netcentral-ui.zip
RUN chown -R ${UNAME}:${GNAME} /netcentral

# make sure netcentral-ui auto-starts
ADD installers/docker/split/image_files/netcentral-ui /etc/init.d/netcentral-ui
RUN ["dos2unix", "/etc/init.d/netcentral-ui"]
RUN chmod +x /etc/init.d/netcentral-ui
RUN rc-update add netcentral-ui default

# expand Node.JS UI
WORKDIR /netcentral/bin/ui
RUN unzip /netcentral/bin/netcentral-ui.zip
RUN rm -rf /netcentral/bin/netcentral-ui.zip
RUN npm install
WORKDIR /netcentral/bin

CMD ["/bin/sh", "-c", "/netcentral/bin/ui_processes.sh & sleep infinity"]