FROM eclipse-temurin:21-jdk-alpine
RUN ["apk", "update"]
RUN ["apk", "add", "bash"]
RUN ["apk", "add", "sudo"]
RUN ["apk", "add", "openrc"]

RUN mkdir -p /run/openrc
RUN touch /run/openrc/softlevel

ARG USER_UID=1000
ARG GROUP_GID=1000
ARG UNAME=netcentral
ARG GNAME=netcentralgroup
RUN addgroup -S -g ${GROUP_GID} ${GNAME} && \
    adduser -S -D -H -u ${USER_UID} -G ${GNAME} ${UNAME}

WORKDIR /netcentral
RUN mkdir -p /netcentral/tmp
RUN mkdir -p /netcentral/tmp/logs
RUN mkdir -p /netcentral/bin

ADD installers/docker/split/image_files/osm-proxy-cache_processes.sh /netcentral/bin/osm-proxy-cache_processes.sh
RUN ["dos2unix", "/netcentral/bin/osm-proxy-cache_processes.sh"]

ADD osm-proxy-cache/target/osm-proxy-cache-1.0.23.jar /netcentral/bin/osm-proxy-cache.jar
RUN chown -R ${UNAME}:${GNAME} /netcentral

ADD installers/docker/split/image_files/config_env.sh /netcentral/bin/config_env.sh
RUN ["dos2unix", "/netcentral/bin/config_env.sh"]
RUN chmod +x /netcentral/bin/config_env.sh

# make sure OSM proxy cache auto-starts
ADD installers/docker/split/image_files/osm-proxy-cache /etc/init.d/osm-proxy-cache
RUN ["dos2unix", "/etc/init.d/osm-proxy-cache"]
RUN chmod +x /etc/init.d/osm-proxy-cache
RUN rc-update add osm-proxy-cache default

CMD ["/bin/sh", "-c", "/netcentral/bin/osm-proxy-cache_processes.sh & sleep infinity"]