micronaut.application.name=osm-proxy-cache

# environment variables needed
# mandatory
netcentral.temp.dir=${NETCENTRAL_OSMPC_TEMP_DIR:/netcentral/tmp}
# must NOT end with /
netcentral.temp.dir.log=${NETCENTRAL_OSMPC_TEMP_DIR:/netcentral/tmp}/logs
# optional
micronaut.server.port=${NETCENTRAL_OSMPC_HTTP_PORT:8889}
micronaut.server.ssl.port=${NETCENTRAL_OSMPC_HTTPS_PORT:4449}
# end environment variables needed

osm.endpoint.format=https://tile.openstreetmap.org/%s/%s/%s.png
osm.refresh.tile.days=60
osm.config=${NETCENTRAL_OSMPC_CONFIG:proxycache}
osm.precache.queue.size=100

micronaut.serde.serialization.inclusion=ALWAYS
micronaut.data.jdbc.connection.read-only=false

threads.count=2
micronaut.security.authentication=session
micronaut.security.redirect.login-success=/
micronaut.security.redirect.login-failure=/authFailed
micronaut.server.cors.enabled=true
micronaut.metrics.enabled=true
micronaut.executors.io.fixed.n-threads=2

# support information
netcentral.support.contact.name=John Rokicki
netcentral.support.contact.callsign=KC1VMZ
netcentral.support.contact.email=kc1vmz@gmail.com

# mysql database configuration
datasources.default.db-type=mysql
datasources.default.driver-class-name=com.mysql.cj.jdbc.Driver
datasources.default.dialect=MYSQL
datasources.default.url=jdbc:mysql://${NETCENTRAL_OSMPC_MYSQL_HOST:localhost}:${NETCENTRAL_OSMPC_MYSQL_PORT:3306}/${NETCENTRAL_OSMPC_MYSQL_DBNAME:netcentral_osmproxycache}
datasources.default.username=${NETCENTRAL_OSMPC_MYSQL_USERNAME:netcentral_osmproxycache}
datasources.default.password=${NETCENTRAL_OSMPC_MYSQL_PASSWORD:netcentral_osmproxycache}
liquibase.datasources.default.change-log=classpath\:db/liquibase-changelog.xml
